name: Deploy Book Store Backend Service
on:
  push:
    branches:
      - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            systemctl_service_name: bookstore
            message: |
              [${{ github.event.head_commit.committer.name }}](https://github.com/${{github.event.head_commit.committer.username}}) pushed new commit: 
              `[ ${{github.event.head_commit.message}} ]` 
              to [${{ github.event.repository.name }}](https://github.com/${{github.event.repository.html_url}}) 
        steps: 
          - uses: actions/checkout@v4
          - name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v4.3.0
            with:
              dotnet-version: "9.0.x"
              include-prerelease: false

          - name: Build
            run: dotnet build -c Release

          - name: Publish
            run: dotnet publish -c Release -o deploy

          - name: stop dotnet services
            uses: garygrossgarten/github-action-ssh@release
            with:
                command: sudo systemctl stop ${{ env.systemctl_service_name }}
                host: ${{ secrets.SSH_HOST }}
                port: 22
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
            
          - name: copy via ssh
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              port: 22
              username: ${{ secrets.SSH_USERNAME }}
              password: ${{ secrets.SSH_PASSWORD }}
              source: deploy/*
              target: "/var/www/backend"
              overwrite: true
              rm: false
              debug: true # Enable debugging
            
          - name: start dotnet services
            uses: garygrossgarten/github-action-ssh@release
            with:
              command: sudo systemctl start --no-block ${{ env.systemctl_service_name }}
              host: ${{ secrets.SSH_HOST }}
              port: 22
              username: ${{ secrets.SSH_USERNAME }}
              password: ${{ secrets.SSH_PASSWORD }}

        
          - name: send notification to telegram
            uses: appleboy/telegram-action@master
            with:
                # to: -1002235899879
                to: ${{ secrets.TELEGRAM_ID }}
                token: ${{ secrets.BOT_TOKEN }}
                message: ${{ env.message }}
                format: markdown
                disable_web_page_preview: true
